language: go

go:
  - 1.8.x

install:
  - go mod download
  - go install github.com/alecthomas/gometalinter
  - gometalinter --install
  - go install github.com/wadey/gocovmerge

script:
  - gometalinter --vendor --disable-all --enable=vet --enable=goimports --enable=vetshadow --enable=golint --enable=ineffassign --enable=goconst --tests ./...
  - ./run-tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
